apiVersion: apps/v1
kind: Deployment
metadata:
  name: impc-nextjs-frontend
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: 655093420076.dkr.ecr.eu-west-2.amazonaws.com/impc-nextjs-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: SERVER_API_ROOT
              value: https://nginx.mousephenotype-dev.org/data
---
apiVersion: v1
kind: Service
metadata:
  name: impc-nextjs-frontend
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31290
