import { render, screen, waitFor } from '@testing-library/react';
import BodyWeightDataComparison from "@/components/Data/DataComparison/BodyWeightDataComparison";
import { Dataset } from "@/models";
import userEvent from "@testing-library/user-event";

const datasets: Array<Dataset> = [
  {
    "id": "667967dc1590f1091643035f",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "CCP_RC2_Dbn1",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6NCrl",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "CCP-IMG",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "CCP-IMG",
    "projectName": "CCP-IMG",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "ac5d9c528fe829b68fd31bfd322cc43c",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2683688",
    "strainName": "C57BL/6NCrl",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 27182,
      "femaleControlMean": 20.7423164226326,
      "femaleControlSd": 3.01336199531763,
      "femaleMutantCount": 121,
      "femaleMutantMean": 20.3332231404959,
      "femaleMutantSd": 2.52506442652989,
      "maleControlCount": 29902,
      "maleControlMean": 25.1740468530533,
      "maleControlSd": 3.81677550106845,
      "maleMutantCount": 139,
      "maleMutantMean": 25.0260431654676,
      "maleMutantSd": 2.67627299215869
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "667956dcf93472cb403f6082",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "H-DBN1-A05-TM1B",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6NTac",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "MRC Harwell",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "MRC Harwell",
    "projectName": "BaSH",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "e2ca2e028c099a01b68dcf9d12d4a998",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2164831",
    "strainName": "C57BL/6NTac",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 58261,
      "femaleControlMean": 23.8935660733595,
      "femaleControlSd": 5.86300718678081,
      "femaleMutantCount": 108,
      "femaleMutantMean": 23.5162037037037,
      "femaleMutantSd": 3.73498857549144,
      "maleControlCount": 58253,
      "maleControlMean": 28.9650669665082,
      "maleControlSd": 6.83414404642204,
      "maleMutantCount": 82,
      "maleMutantMean": 27.8675609756098,
      "maleMutantSd": 4.40250000833578
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "66796562707a3ae1045d1c4c",
    "alleleAccessionId": "MGI:4363390",
    "alleleName": "targeted mutation 1a, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1a(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "MCKS",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6N",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "WTSI",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "WTSI",
    "projectName": "MGP",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "4089eed778598fae19ee59d78e8332f8",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2159965",
    "strainName": "C57BL/6N",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 39486,
      "femaleControlMean": 23.3888081851796,
      "femaleControlSd": 4.72219333012864,
      "femaleMutantCount": 94,
      "femaleMutantMean": 20.7457446808511,
      "femaleMutantSd": 3.18867838917553,
      "maleControlCount": 46665,
      "maleControlMean": 29.2497160612879,
      "maleControlSd": 5.69375445236241,
      "maleMutantCount": 119,
      "maleMutantMean": 28.2697478991597,
      "maleMutantSd": 3.81052411141869
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "66796075b1bae7c727b81805",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "MCKS-3",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6NTac",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "HMGU",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "HMGU",
    "projectName": "Helmholtz GMC",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "7e9a518adcb7c3359a0488e493eb1c34",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2164831",
    "strainName": "C57BL/6NTac",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 20734,
      "femaleControlMean": 23.6010718626411,
      "femaleControlSd": 6.39004649562284,
      "femaleMutantCount": 172,
      "femaleMutantMean": 20.393023255814,
      "femaleMutantSd": 3.76781664475089,
      "maleControlCount": 21513,
      "maleControlMean": 28.2721775670525,
      "maleControlSd": 6.90102587683438,
      "maleMutantCount": 159,
      "maleMutantMean": 27.4798742138365,
      "maleMutantSd": 5.63998810343271
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "6679565c0616af1fae239031",
    "alleleAccessionId": "MGI:4363390",
    "alleleName": "targeted mutation 1a, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1a(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "EPD0211_3_A05",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6N",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "WTSI",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "WTSI",
    "projectName": "MGP",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "MGP",
    "resourceName": "MGP",
    "sex": null,
    "zygosity": "homozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "f0a55b23121375a822e8f3894894d604",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2159965",
    "strainName": "C57BL/6N",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 39486,
      "femaleControlMean": 23.3888081851796,
      "femaleControlSd": 4.72219333012864,
      "femaleMutantCount": 58,
      "femaleMutantMean": 19.9448275862069,
      "femaleMutantSd": 6.0747152821532,
      "maleControlCount": 46665,
      "maleControlMean": 29.2497160612879,
      "maleControlSd": 5.69375445236241,
      "maleMutantCount": 48,
      "maleMutantMean": 21.41875,
      "maleMutantSd": 5.43756266777289
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "66795d3172906745a9d0729c",
    "alleleAccessionId": "MGI:4363390",
    "alleleName": "targeted mutation 1a, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1a(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "MCKS",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6N",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "WTSI",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "WTSI",
    "projectName": "MGP",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "homozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "1d467fbe83eb71d4db6dfde665eb0950",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2159965",
    "strainName": "C57BL/6N",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 39486,
      "femaleControlMean": 23.3888081851796,
      "femaleControlSd": 4.72219333012864,
      "femaleMutantCount": 39,
      "femaleMutantMean": 19.6923076923077,
      "femaleMutantSd": 2.67772336680804,
      "maleControlCount": 46665,
      "maleControlMean": 29.2497160612879,
      "maleControlSd": 5.69375445236241,
      "maleMutantCount": 17,
      "maleMutantMean": 25.2235294117647,
      "maleMutantSd": 3.27615044903403
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "667955f9fd1c1dd5d3c64e0c",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "DBNNB",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6N",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "BCM",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "BCM",
    "projectName": "BaSH",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "a6c459ae51b4c1a7bdc8309ba8284101",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2159965",
    "strainName": "C57BL/6N",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 19487,
      "femaleControlMean": 21.1593712087546,
      "femaleControlSd": 4.54904646862506,
      "femaleMutantCount": 120,
      "femaleMutantMean": 20.2583333333333,
      "femaleMutantSd": 3.14248692752028,
      "maleControlCount": 18910,
      "maleControlMean": 26.3245647276573,
      "maleControlSd": 6.26203071699009,
      "maleMutantCount": 129,
      "maleMutantMean": 25.0387674418605,
      "maleMutantSd": 4.77875227326592
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "6679597089f60217ef017d68",
    "alleleAccessionId": "MGI:6158479",
    "alleleName": "endonuclease-mediated mutation 2, Mouse Biology Program, UC Davis",
    "alleleSymbol": "Dbn1<em2(IMPC)Mbp>",
    "classificationTag": null,
    "colonyId": "CR992",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6NCrl",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "UC Davis",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "UC Davis",
    "projectName": "DTCC",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "b82e0227fa7b9589908ce6315300ba1b",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2683688",
    "strainName": "C57BL/6NCrl",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 34706,
      "femaleControlMean": 24.5308257106076,
      "femaleControlSd": 6.82040102980732,
      "femaleMutantCount": null,
      "femaleMutantMean": null,
      "femaleMutantSd": null,
      "maleControlCount": 37382,
      "maleControlMean": 30.4185048954328,
      "maleControlSd": 7.34778593243743,
      "maleMutantCount": 14,
      "maleMutantMean": 24.8392857142857,
      "maleMutantSd": 2.45824660553541
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "66795d0b21635dd8efc05764",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "ET6714_TCP",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6NCrl",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "TCP",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "Crl",
    "projectName": "DTCC",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "2239129a28b6ffa3a847f349b2cf6c62",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2683688",
    "strainName": "C57BL/6NCrl",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 19234,
      "femaleControlMean": 22.5761505667048,
      "femaleControlSd": 5.79251501576558,
      "femaleMutantCount": 130,
      "femaleMutantMean": 19.5214615384615,
      "femaleMutantSd": 2.66975744667763,
      "maleControlCount": 18583,
      "maleControlMean": 27.8889721788732,
      "maleControlSd": 6.18225116417369,
      "maleMutantCount": 129,
      "maleMutantMean": 26.8057364341085,
      "maleMutantSd": 3.39032902514495
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "6679612d96a5e7afa32fcffc",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "JR21507",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6NJ",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "JAX",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "JAX",
    "projectName": "JAX",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "1db2215fda7fb5a0254c36ef9472b365",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:3056279",
    "strainName": "C57BL/6NJ",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 59112,
      "femaleControlMean": 22.4257851197726,
      "femaleControlSd": 6.85554594585579,
      "femaleMutantCount": 125,
      "femaleMutantMean": 19.49952,
      "femaleMutantSd": 3.56590436793954,
      "maleControlCount": 58039,
      "maleControlMean": 28.0502312238323,
      "maleControlSd": 8.75183034943538,
      "maleMutantCount": 143,
      "maleMutantMean": 24.4803496503497,
      "maleMutantSd": 3.72861327025708
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "6679582db32dec87634b6848",
    "alleleAccessionId": "MGI:6257430",
    "alleleName": "endonuclease-mediated mutation 1, Baylor College of Medicine",
    "alleleSymbol": "Dbn1<em1(IMPC)Bay>",
    "classificationTag": null,
    "colonyId": "DBNCB",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6N",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "BCM",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "BCM",
    "projectName": "BaSH",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "homozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "990b0fae86ac70da340dfcec7775ecd2",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2159965",
    "strainName": "C57BL/6N",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 19487,
      "femaleControlMean": 21.1593712087546,
      "femaleControlSd": 4.54904646862506,
      "femaleMutantCount": 145,
      "femaleMutantMean": 19.7605517241379,
      "femaleMutantSd": 3.56927569280721,
      "maleControlCount": 18910,
      "maleControlMean": 26.3245647276573,
      "maleControlSd": 6.26203071699009,
      "maleMutantCount": 149,
      "maleMutantMean": 24.3558657718121,
      "maleMutantSd": 4.38946607702127
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "66796051eaf80728c64e45c4",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "DBNNB",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6N",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "BCM",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "BCM",
    "projectName": "BaSH",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "homozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "1c4b1b18545626ff15d01b04d8438a12",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2159965",
    "strainName": "C57BL/6N",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 19487,
      "femaleControlMean": 21.1593712087546,
      "femaleControlSd": 4.54904646862506,
      "femaleMutantCount": 16,
      "femaleMutantMean": 20.9375,
      "femaleMutantSd": 2.5943207203428,
      "maleControlCount": 18910,
      "maleControlMean": 26.3245647276573,
      "maleControlSd": 6.26203071699009,
      "maleMutantCount": 16,
      "maleMutantMean": 28.275,
      "maleMutantSd": 3.7032418230518
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "6679642678bb48589c0f15c7",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "RIKEN-Dbn1-A05_",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6NTac",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "RBRC",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "RBRC",
    "projectName": "RBRC",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "ea851ade4281d61bfb62d299427b4158",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2164831",
    "strainName": "C57BL/6NTac",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 8685,
      "femaleControlMean": 22.2681865284974,
      "femaleControlSd": 2.9863631396205,
      "femaleMutantCount": 128,
      "femaleMutantMean": 22.48984375,
      "femaleMutantSd": 2.8480920493991,
      "maleControlCount": 8669,
      "maleControlMean": 26.4498442726958,
      "maleControlSd": 3.72230075035175,
      "maleMutantCount": 128,
      "maleMutantMean": 25.19375,
      "maleMutantSd": 3.89469152144866
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "66795b45353570c35e38c9dd",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "IP00005427a",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6N",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "ICS",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "ICS",
    "projectName": "Phenomin",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "cf0f920f9c5a87ea1917de3c1b169c9a",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2159965",
    "strainName": "C57BL/6N",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 9119,
      "femaleControlMean": 20.70700668933,
      "femaleControlSd": 2.59981268468685,
      "femaleMutantCount": 74,
      "femaleMutantMean": 20.4492027027027,
      "femaleMutantSd": 2.45355004739277,
      "maleControlCount": 9637,
      "maleControlMean": 24.7068858981011,
      "maleControlSd": 3.33057378484622,
      "maleMutantCount": 73,
      "maleMutantMean": 24.9990273972603,
      "maleMutantSd": 3.26501917202387
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "66795c1e97ef86aad2d60191",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "MUCL",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6N",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "WTSI",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "WTSI",
    "projectName": "MGP",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "769e6c46a134617224caa0ac0c90cc05",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2159965",
    "strainName": "C57BL/6N",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 39486,
      "femaleControlMean": 23.3888081851796,
      "femaleControlSd": 4.72219333012864,
      "femaleMutantCount": 95,
      "femaleMutantMean": 21.0726315789474,
      "femaleMutantSd": 3.37274564915378,
      "maleControlCount": 46665,
      "maleControlMean": 29.2497160612879,
      "maleControlSd": 5.69375445236241,
      "maleMutantCount": 124,
      "maleMutantMean": 27.8758064516129,
      "maleMutantSd": 4.60899387584756
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "667964fdfa3ff8a0ec555610",
    "alleleAccessionId": "MGI:5645712",
    "alleleName": "endonuclease-mediated mutation 1, Jackson",
    "alleleSymbol": "Dbn1<em1(IMPC)J>",
    "classificationTag": null,
    "colonyId": "JR27202",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6NJ",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "JAX",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "JAX",
    "projectName": "JAX",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "homozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "5d9fcd15f25b98623651e841525fd666",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:3056279",
    "strainName": "C57BL/6NJ",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 59112,
      "femaleControlMean": 22.4257851197726,
      "femaleControlSd": 6.85554594585579,
      "femaleMutantCount": 153,
      "femaleMutantMean": 19.2472549019608,
      "femaleMutantSd": 3.61010464844932,
      "maleControlCount": 58039,
      "maleControlMean": 28.0502312238323,
      "maleControlSd": 8.75183034943538,
      "maleMutantCount": 131,
      "maleMutantMean": 24.1059541984733,
      "maleMutantSd": 4.69855653425373
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "667956353ca28728f8bf410a",
    "alleleAccessionId": "MGI:5501061",
    "alleleName": "targeted mutation 1b, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1b(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "ET6714",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6NCrl",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "UC Davis",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "Crl",
    "projectName": "DTCC",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "IMPC",
    "resourceName": "IMPC",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "5f970b01fb8fdac9400635f7c52e8e93",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2683688",
    "strainName": "C57BL/6NCrl",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 34706,
      "femaleControlMean": 24.5308257106076,
      "femaleControlSd": 6.82040102980732,
      "femaleMutantCount": 68,
      "femaleMutantMean": 20.7986764705882,
      "femaleMutantSd": 2.13317498943652,
      "maleControlCount": 37382,
      "maleControlMean": 30.4185048954328,
      "maleControlSd": 7.34778593243743,
      "maleMutantCount": 119,
      "maleMutantMean": 26.466218487395,
      "maleMutantSd": 2.94609911336279
    },
    "topLevelPhenotypes": [

    ],
  },
  {
    "id": "667959cda25c8d532958e565",
    "alleleAccessionId": "MGI:4363390",
    "alleleName": "targeted mutation 1a, Wellcome Trust Sanger Institute",
    "alleleSymbol": "Dbn1<tm1a(KOMP)Wtsi>",
    "classificationTag": null,
    "colonyId": "EPD0211_3_A05",
    "dataType": "time_series",
    "geneSymbol": "Dbn1",
    "geneticBackground": "involves: C57BL/6N",
    "intermediatePhenotypes": [

    ],
    "lifeStageAcc": "IMPCLS:0005",
    "lifeStageName": "Early adult",
    "metadataGroup": "d41d8cd98f00b204e9800998ecf8427e",
    "metadataValues": [

    ],
    "mgiGeneAccessionId": "MGI:1931838",
    "parameterName": "Body weight curve",
    "parameterStableId": "IMPC_BWT_008_001",
    "parameterStableKey": 27192,
    "phenotypeSex": null,
    "phenotypingCentre": "WTSI",
    "pipelineName": "IMPC Pipeline",
    "pipelineStableId": "IMPC_001",
    "pipelineStableKey": 7,
    "potentialPhenotypes": [

    ],
    "procedureGroup": "IMPC_BWT",
    "procedureName": "Body Weight",
    "procedureStableId": "IMPC_BWT_001",
    "procedureStableKey": 623,
    "productionCentre": "WTSI",
    "projectName": "MGP",
    "reportedEffectSize": null,
    "reportedPValue": null,
    "unit": {
      "x": null,
      "y": "g"
    },
    "resourceFullName": "MGP",
    "resourceName": "MGP",
    "sex": null,
    "zygosity": "heterozygote",
    "significant": false,
    "significantPhenotype": null,
    "softWindowing": {
      "bandwidth": null,
      "doeNote": null,
      "minObsRequired": null,
      "numberOfDoe": null,
      "peaks": null,
      "shape": null,
      "threshold": null,
      "totalObsOrWeight": null
    },
    "statisticalMethod": {
      "name": null,
      "attributes": {
        "femaleEffectSize": null,
        "femaleKoEffectPValue": null,
        "femaleKoEffectStderrEstimate": null,
        "femaleKoParameterEstimate": null,
        "femalePercentageChange": null,
        "maleKoEffectPValue": null,
        "maleKoEffectStderrEstimate": null,
        "maleKoParameterEstimate": null,
        "malePercentageChange": null,
        "genotypeEffectPValue": null,
        "genotypeEffectStderrEstimate": null,
        "group1Genotype": null,
        "group1ResidualsNormalityTest": null,
        "group2Genotype": null,
        "group2ResidualsNormalityTest": null,
        "interactionEffectPValue": null,
        "interactionSignificant": null,
        "interceptEstimate": null,
        "interceptEstimateStderrEstimate": null,
        "maleEffectSize": null,
        "sexEffectPValue": null,
        "sexEffectParameterEstimate": null,
        "sexEffectStderrEstimate": null,
        "batchSignificant": null,
        "varianceSignificant": null
      }
    },
    "datasetId": "3f1654c33e68a93a0c8486ee9f568be7",
    "status": "NotProcessed",
    "strainAccessionId": "MGI:2159965",
    "strainName": "C57BL/6N",
    "summaryStatistics": {
      "bothMutantCount": null,
      "bothMutantMean": null,
      "bothMutantSd": null,
      "femaleControlCount": 39486,
      "femaleControlMean": 23.3888081851796,
      "femaleControlSd": 4.72219333012864,
      "femaleMutantCount": 81,
      "femaleMutantMean": 22.8703703703704,
      "femaleMutantSd": 7.1993306015984,
      "maleControlCount": 46665,
      "maleControlMean": 29.2497160612879,
      "maleControlSd": 5.69375445236241,
      "maleMutantCount": 96,
      "maleMutantMean": 29.24375,
      "maleMutantSd": 8.3929019195734
    },
    "topLevelPhenotypes": [

    ],
  }
];

describe('Bodyweight data comparison component', () => {
  it('renders deduplicated data', async () => {
    render(<BodyWeightDataComparison data={datasets} />);
    const rows = await screen.findAllByRole('row');
    // 6 because includes the header ones
    expect(rows.length).toEqual(12);
    const headers = await screen.findAllByRole('columnheader');
    expect(headers.length).toEqual(5);
  });

  it('automatically selects the first row if not provided from props', async () => {
    const selectParamMock = jest.fn();
    render(<BodyWeightDataComparison data={datasets} onSelectParam={selectParamMock} selectedKey={""} />);
    await waitFor(() => {
      expect(selectParamMock).toHaveBeenCalled();
    });
  });

  it('emits the key of the row if the users clicks on it', async () => {
    const user = userEvent.setup();
    const selectParamMock = jest.fn();
    render(<BodyWeightDataComparison data={datasets} onSelectParam={selectParamMock} selectedKey={""} />);
    const rows = await screen.findAllByRole('row');
    // first 2 are the header ones
    await user.click(rows[4]);
    await waitFor(() => {
      expect(selectParamMock).toHaveBeenCalledTimes(2);
      expect(selectParamMock).toHaveBeenLastCalledWith(
        "-MGI:5501061-IMPC_BWT_008_001-homozygote-BCM-DBNNB-Early adult-null"
      );
    });
  });
});